"""empty message

Revision ID: 828102d6d449
Revises: b3f7f99c70e7
Create Date: 2024-05-10 14:18:36.767222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828102d6d449'
down_revision = 'b3f7f99c70e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_date', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('update_date')

    # ### end Alembic commands ###
